### ISSUE TITLE
Does the pypi 0.4.0 version come from the master branch?

### ISSUE THREAD

**Issue by jamaalscarlett** [web-push-libs/encrypted-content-encoding#13]
I have a small python module that I am using to test the mozilla web push api.  Version 0.2.0 worked fine; however after upgrading to 0.4.0, the code no longer works.  I took a look at the master branch and I couldn't find a change that would explain the failure.

**Comment by martinthomson** [comment]
0.4.0 tracks the latest spec, which includes a different padding size (2 octets instead of just 1).

I've just uploaded 0.4.1, which includes an extra argument, `padSize`, which you can use to set the smaller padding size.

**Comment by martinthomson** [comment]
And yes, I realize that I neglected to push.  Does 0.4.1 address the issue for you?

**Comment by jamaalscarlett** [comment]
0.4.1 did not work for me.  I'm fine with pinning the version to 0.2.0 for now.

**Comment by martinthomson** [comment]
To use 0.4.1 with Firefox, you need to pass `padSize: 1` in the parameters.

**Comment by martinthomson** [comment]
@jamaalscarlett, #15 has just landed with a fix that I think should fix your problem.

**Comment by jamaalscarlett** [comment]
Thanks, I will try it and let you know.

**Comment by martinthomson** [comment]
0.5.0 released
