### ISSUE TITLE
import HKDF error due to GAE sandbox lockdown 

### ISSUE THREAD

**Issue by axacheng** [web-push-libs/encrypted-content-encoding#22]
Hi guys:

[Just a FYI and probably this bug is quite challenge to be fixed.]

I got **ImportError: No module named cryptography.hazmat.bindings._constant_time** error while importing http_ece due to GAE doesn't support most of C extension libraries.

Reference:
[cryptography issue 2161](https://github.com/pyca/cryptography/issues/2612)

**Comment by martinthomson** [comment]
Yep, not a lot we can do about this without a pretty significant amount of work.  Thanks for the heads-up.  Hopefully this will serve as documentation for others who are stuck using services that don't support running code.
