### ISSUE TITLE
Padding and record size for aes128gcm

### ISSUE THREAD

**Issue by ghost** [web-push-libs/encrypted-content-encoding#32]
I'm working on generating some test vectors with different pad and record sizes for ecec and Firefox, and I have a couple of questions.

* If any padding is specified, should the minimum rs be 19? (Auth tag, delimiter, 1 byte of plaintext, and 1 byte of padding). Otherwise, we end up with unpadded and padding-only blocks.
* Does the standard allow padding-only blocks? This library rejects them, but I didn't see that restriction in the draft.

**Comment by martinthomson** [comment]
The absolute minimum value for `rs` is 18.  As you say, that means choosing between an octet of padding or an octet of plaintext, but that's OK.  This library attempts to always make progress when padding, including at least one octet in every record, but that's just my choice.

The padding-only thing is just a bug.  I'll see if I can fix it.

**Comment by martinthomson** [comment]
The library should now accept and generate rs=18 records.  I've added some tests to verify this.  Note that the python library doesn't add padding, but the nodejs one can.  I've verified that it will correctly pad rs=18 records.
