### ISSUE TITLE
pyelliptic is deprecated

### ISSUE THREAD

**Issue by balloob** [web-push-libs/encrypted-content-encoding#33]
The dependency pyelliptic has been deprecated and should probably be replaced.

A workaround for now would be to pin the version of pyelliptic to 1.5.7. [(that fixed it for us)](https://github.com/home-assistant/home-assistant/pull/7310)

----

Background info:

Discovered it because Home Assistant CI started failing after pyelliptic 1.5.8 was released today which removes the ECC part: https://github.com/yann2192/pyelliptic/commit/71577149fc0e0031e967fd6732947d2f4ac9144c

[CI logs showing http-ece import error](https://travis-ci.org/home-assistant/home-assistant/jobs/225754860#L411)

![image](https://cloud.githubusercontent.com/assets/1444314/25416665/cecd54e0-29f3-11e7-9272-12c88b64e046.png)

**Comment by martinthomson** [comment]
I've fixed this with the same fix in 0.7.3.  #34 tracks moving to using cryptography for ECDH now that they finally have support.

**Comment by martinthomson** [comment]
You might like to try out the release version.  I will push a version to pypi in a short while.

**Comment by balloob** [comment]
Thanks!

**Comment by Flimm** [comment]
For everyone who is confused like me, this issue has been closed because the fix has been merged into `master`, but the latest release on PyPI does not yet contain this fix. Could @martinthomson release a new version on PyPI? Thanks.

**Comment by martinthomson** [comment]
I've published 1.0.0.  Apologies for missing the push.
