### ISSUE TITLE
Update to cryptography 1.8.1

### ISSUE THREAD

**Issue by jrconlin** [web-push-libs/encrypted-content-encoding#36]
A security release of openssl broke one of the calls https://github.com/pyca/cryptography/issues/2750, which will prevent http_ece from installing if there's an existing library that uses a later install of cryptography. 

Please update the dependency from 1.1.0 to 1.8.1

**Comment by martinthomson** [comment]
JR, PR?

**Comment by jrconlin** [comment]
Added.
