### ISSUE TITLE
pip install issue

### ISSUE THREAD

**Issue by mwent-cray** [web-push-libs/encrypted-content-encoding#40]
Hi I'm having an issue installing this package:

```
❯ pip install --user http_ece
Collecting http_ece
  Using cached http_ece-1.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    error in http_ece setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers

    ----------------------------------------
```

Any clue why this is happening?

**Comment by mwent-cray** [comment]
Issue seems to be that: 
```
install_requires=[
        'cryptography~=1.9',
    ],
```
Where the _**~=**_ isn't handled properly, and works with _**>=**_

**Comment by mwent-cray** [comment]
`~= 1.9        # Compatible release. Same as >= 1.9, == 1.*`

**Comment by martinthomson** [comment]
I'm not sure what is going on here.  I have an ancient version of pip on one of my machines (7.1.2) and it understands the `~=` well enough.

**Comment by mwent-cray** [comment]
Turns out to be a different issue. It is Mac OS X related...
Apparently Mac OS X runs a different SSL library than needed (needed is OpenSSL)
Turns out that http_ece tries to install it's own version (1.8 if I'm not mistaken) of cryptography. 
Cryptography needs to be compiled and for that version needs openssl to be available on the system.

Managed to fix this issue by manually installing openssl on mac os x
`brew install openssl`
[https://github.com/pyca/cryptography/issues/2692#issuecomment-272773481](url)
