### ISSUE TITLE
Wrong version pinning in setup.py

### ISSUE THREAD

**Issue by mammuth** [web-push-libs/encrypted-content-encoding#42]
I think your version pinning of the cryptography package is syntactically wrong, isn't it. This probably prevents installing pywebpush via pip:
```
pip3 install pywebpush
Collecting pywebpush
  Using cached pywebpush-1.0.5.tar.gz
Requirement already satisfied: cryptography<1.10,>=1.8.1 in /srv/homeassistant/lib/python3.4/site-packages (from pywebpush)
Collecting http-ece>=1.0.1 (from pywebpush)
  Using cached http_ece-1.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    error in http_ece setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-q1sixmvm/http-ece/

```

**Comment by halkeye** [comment]
I'm also trying to install this from homeassistant. 

I've found out it can be fixed by upgrading setuptools

```
source /srv/homeassistant/bin/activate
pip install setuptools --upgrade
pip install pywebpush==1.0.5
```

**Comment by martinthomson** [comment]
This is a difficult one to fix here.  The specification is correct according to [the specification](https://www.python.org/dev/peps/pep-0440/#compatible-release).

See https://github.com/web-push-libs/encrypted-content-encoding/issues/40#issuecomment-310425265 for a fix that involves updating the openssl version on the system.  That said, I'm not sure that this is the answer given that cryptography seems to be installed according to the log here.

**Comment by martinthomson** [comment]
I just pushed a new point release that uses the same syntax as `pywebpush`.  Hopefully the problem will disappear.
