### ISSUE TITLE
Remove saved.keymap from ece.js

### ISSUE THREAD

**Issue by aliams** [web-push-libs/encrypted-content-encoding#45]
I noticed that https://github.com/web-push-libs/encrypted-content-encoding/blob/master/nodejs/ece.js#L264 still uses "saved" even though it's been removed.

**Comment by aliams** [comment]
cc @martinthomson

**Comment by martinthomson** [comment]
@aliams, yeah, that's a simple bug.  Do you think that you could create a PR?

**Comment by aliams** [comment]
I just filed this pull request: https://github.com/web-push-libs/encrypted-content-encoding/pull/46. I hope just removing it was what was intended.

**Comment by martinthomson** [comment]
I think that will do for now.  There are probably some other cleanups that would make things slightly better, but this gets rid of the glaring undefined reference problem.
