### ISSUE TITLE
PHP implementation

### ISSUE THREAD

**Issue by Minishlink** [web-push-libs/encrypted-content-encoding#5]
Hi, I was wondering if I could start a PHP implementation.

The problem is that there is no library at the moment that handle AES GCM mode. The PHP binding of OpenSSL lists GCM as available but there is currently no way to retrieve the authentication tag (see [bug issue](https://bugs.php.net/bug.php?id=67304)).

Is there a way to support your spec without GCM ? I guess not, but I need to ask. :)

My final goal is to be able to encrypt payload for my [WebPush](https://github.com/Minishlink/web-push) PHP library.

**Comment by martinthomson** [comment]
You will need GCM for sure.  I would talk to @beverloo about this though, I think that there might be something in progress.

**Comment by marco-c** [comment]
https://github.com/beverloo/php-ece (but it isn't meant for production usage).
