### ISSUE TITLE
master -> main branch

### ISSUE THREAD

**Issue by martinthomson** [web-push-libs/encrypted-content-encoding#71]
@jrconlin Are you able to do a branch rename for me?

**Comment by jrconlin** [comment]
There's already a `main` branch from 4 years ago. It's probably best to land to `master` then rename master to main after.

**Comment by martinthomson** [comment]
I don't see a `main` (I cleaned up a bunch of branches, but that wasn't one of them).  Renaming will cause PRs to be updated, so I don't think that holds us back from making a change here.

**Comment by jrconlin** [comment]
Yeah, just removed the old "main" and updated settings to use "master" it'll take a bit on github, then you should be able to
```
git branch -m master main
git fetch origin
git branch -u main main
git remote set-head origin -a
```

**Comment by jrconlin** [comment]
Ok, should be done by now.
