### ISSUE TITLE
1.2.1 is not on pypi

### ISSUE THREAD

**Issue by tastytea** [web-push-libs/encrypted-content-encoding#79]
possibly because the tag is `1.2.1` without the `v` in front, like the other release tags?

**Comment by jrconlin** [comment]
Sadly, I don't have access to the project on pipy, so @martinthomson needs to publish it.

**Comment by martinthomson** [comment]
Ack.  Done.  @jrconlin we should chat next week about how to manage this better.  I can probably setup CI; I already have a script that works fine, but I'm concerned about the integrity of the necessary secrets.

**Comment by jrconlin** [comment]
Ah, Sadly, I won't be in Dublin. I know that for a bunch of our normal stuff, we use Circle accounts to hold the secrets. I'm a bit tempted to see if we can set up something similar here, but not sure the best approach. I'll chase a few ideas and see what I can come up with after everyone gets back.
